// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkKbeC4IwKwNw-NVmGRlEETopr1KwlkLc',
    appId: '1:776756715965:web:af3e45eaf7aa77692372d4',
    messagingSenderId: '776756715965',
    projectId: 'test-andromeda-61de7',
    authDomain: 'test-andromeda-61de7.firebaseapp.com',
    storageBucket: 'test-andromeda-61de7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1i8j4tjCln7Nj-PXQAQS4CkyQFAY_GTY',
    appId: '1:776756715965:android:27becc4efa6730f62372d4',
    messagingSenderId: '776756715965',
    projectId: 'test-andromeda-61de7',
    storageBucket: 'test-andromeda-61de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsY4PL_QmYwa4By7kKZkbDx6jY4_dYWP4',
    appId: '1:776756715965:ios:65c5ecfaacc21c9d2372d4',
    messagingSenderId: '776756715965',
    projectId: 'test-andromeda-61de7',
    storageBucket: 'test-andromeda-61de7.appspot.com',
    iosBundleId: 'com.example.minorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsY4PL_QmYwa4By7kKZkbDx6jY4_dYWP4',
    appId: '1:776756715965:ios:65c5ecfaacc21c9d2372d4',
    messagingSenderId: '776756715965',
    projectId: 'test-andromeda-61de7',
    storageBucket: 'test-andromeda-61de7.appspot.com',
    iosBundleId: 'com.example.minorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkKbeC4IwKwNw-NVmGRlEETopr1KwlkLc',
    appId: '1:776756715965:web:fc959b579023b9bb2372d4',
    messagingSenderId: '776756715965',
    projectId: 'test-andromeda-61de7',
    authDomain: 'test-andromeda-61de7.firebaseapp.com',
    storageBucket: 'test-andromeda-61de7.appspot.com',
  );
}
